### PR TITLE
Add records

### PR DESCRIPTION
**Pull request by KrzysztofP90**
Do You want it?

### CODE REVIEW

**Comment by KrzysiekJodlowski** [comment]
Do I want what?

**Comment by mihuwis** [comment]
we need more records!!!

**Comment by KrzysiekJodlowski** [comment]
I agree with Mihu, make it more:)

**Comment by KrzysztofP90** [comment]
Now it's 100 million records

**Comment by KrzysiekJodlowski** [comment]
I'ts good now

**Pull request merged**
